### ISSUE TITLE
Errors in HA log

### ISSUE THREAD

**Issue by pcl101** [codingcyclist/ha_strava#22]
Installation went fine. But now I got these errors in my HA log and sensor data does not update.

HA 2020.12.7
Supervisor on Ubuntu 18 / docker

IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range
2021-01-03 16:23:57 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/sensor.py", line 403, in strava_data_update_event_handler
    self._data = event.data["activities"][self._activity_index]
IndexError: list index out of range

**Comment by codingcyclist** [comment]
Hi @pcl101,

let's see what's going on here. The first thing I would check is how many activities you have on your Strava account. Is that number is smaller than the number of concurrent activities which you've configured for the integration?

best,

Simon

**Comment by pcl101** [comment]
You have a keen eye. I salute you Sir!

I've only got one activity in my Strava account ( just starten a trail run today ) and the number of concurrent activities in my configuration is set to 3.

Suggestion : I'll leave the number of activities in my configuration at 3 and see what happens over the next few days as the number of activities in Strava rises.

**Comment by pcl101** [comment]
Update : Got three activities in Strava. Still no luck. Same errors.

Could it be that this integration only works on the paid version of Strava?

**Comment by codingcyclist** [comment]
Hi @pcl101, I'm sorry that you keep having issues with the integration. Are all your three activities either Running, Cycling, or Hiking activities? Unfortunately, those are the only three types of activities which are currently supported by the integration.

**Comment by joelez83** [comment]
Hi,
Everything is solved. Don’t know exactly what happen, but after some rebooting everything went fine. Thanks for answering by the way

Gioele Zingarino
Inviato dal mio iPhone
