### ISSUE TITLE
All Sensor Values = -1

### ISSUE THREAD

**Issue by jlwainwright** [codingcyclist/ha_strava#24]
Hi there. 

Just not able to get this Add-On to return my Strava data. All sensors result in -1:

What could I be doing wrong?

Logger: homeassistant
Source: custom_components/ha_strava/__init__.py:417
First occurred: 11:29:25 (1 occurrences)
Last logged: 11:29:25

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('165.73.102.4', 8123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ha_strava/__init__.py", line 560, in strava_startup_functions
    await renew_webhook_subscription(
  File "/config/custom_components/ha_strava/__init__.py", line 417, in renew_webhook_subscription
    callback_response = await websession.get(url=config_data[CONF_CALLBACK_URL])
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1057, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1026, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 981, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host dieneusels.duckdns.org:8123 ssl:default [Connect call failed ('165.73.102.4', 8123)]

HA Log:
2021-01-09 11:27:14 INFO (MainThread) [custom_components.ha_strava.config_flow] Successfully authenticated
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.setup] Setting up ha_strava
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.setup] Setup of domain ha_strava took 0.0 seconds
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.ha_strava
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.camera] Setting up camera.ha_strava
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_0_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_1_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_2_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_3_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_4_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_5_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_6_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_7_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_8_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_9_0
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Title & Date because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_0_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_1_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_2_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_3_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_4_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_5_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_6_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_7_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_8_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_9_1
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Duration because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_0_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_1_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_2_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_3_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_4_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_5_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_6_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_7_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_8_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_9_2
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Pace because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_0_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_1_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_2_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_3_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_4_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_5_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_6_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_7_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_8_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_9_3
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Distance because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_0_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_1_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_2_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_3_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_4_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_5_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_6_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_7_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_8_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_9_4
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Trophies because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_0_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_1_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_2_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_3_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_4_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_5_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_6_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_7_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_8_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_9_5
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.sensor] Not adding entity Kudos because it's disabled
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_run_distance
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_run_distance
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_run_moving_time
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_run_moving_time
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_run_activity_count
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_run_activity_count
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_ride_distance
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_ride_distance
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_ride_moving_time
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_ride_moving_time
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_ride_activity_count
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_ride_activity_count
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_swim_distance
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_swim_distance
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_swim_moving_time
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_swim_moving_time
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_ytd_swim_activity_count
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ha_strava entity: sensor.strava_stats_summary_all_swim_activity_count
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new camera.ha_strava entity: camera.strava_cam
2021-01-09 11:27:14 INFO (MainThread) [homeassistant.components.camera] Not adding entity strava_cam because it's disabled

**Comment by jlwainwright** [comment]
![strava](https://user-images.githubusercontent.com/17202115/104119362-78355580-5337-11eb-8446-6acc747c7ce5.jpg)

**Comment by BertrumUK** [comment]
I am seeing the same thing now - it was working fine a few days back but is now showing -1 for all the sensors. I have reinstalled and linked to the API again but it is still the same.

**Comment by BertrumUK** [comment]
Ok adding a short walk to Strava and restarting HA to force an update cleared the issue for me.
