### ISSUE TITLE
Exception in log

### ISSUE THREAD

**Issue by stefanroelofs** [codingcyclist/ha_strava#27]
Hi, I get an exception in the log recently:

```
2021-01-25 09:08:52 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_strava/camera.py", line 168, in img_update_handler
    self._urls = {
TypeError: unhashable type: 'slice'
```
I see it every time I reboot HA. 

Everything seems to work fine, so no need to do anything. I just thought I'd share it.

Thanks!

**Comment by bckthomas** [comment]
Same problem here  !

**Comment by tinus20vt** [comment]
Is there an update?
